spring:
  data:
    mongodb:
      auto-index-creation: true
      database: epistimi
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@cluster0.i5gua.mongodb.net/epistimi?retryWrites=true&w=majority
epistimi:
  security:
    jwt-expiry-millis: 900000
    jwt-secret: ${JWT_SECRET}
    password-encoder-strength: 12
