epistimi:
  external-apis:
    nominatim:
      url: https://nominatim.openstreetmap.org/search
  security:
    jwt-expiry-millis: 900000
    jwt-secret: ${JWT_SECRET}
    password-encoder-strength: 12
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/epistimi
    username: epistimi
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      auto-index-creation: true
      database: epistimi
      uri: mongodb://admin:123456@localhost:27017/epistimi?retryWrites=true&w=majority
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            DEBUG
