epistimi:
  security:
    jwt-expiry-millis: 900000
    jwt-secret: ${JWT_SECRET}
    password-encoder-strength: 12
spring:
  data:
    mongodb:
      auto-index-creation: true
      database: epistimi
      uri: mongodb://admin:123456@localhost:27017/epistimi?retryWrites=true&w=majority
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            DEBUG
