export const enum GradeValue {
  UNSATISFACTORY = 'UNSATISFACTORY',
  ACCEPTABLE_MINUS = 'ACCEPTABLE_MINUS',
  ACCEPTABLE = 'ACCEPTABLE',
  ACCEPTABLE_PLUS = 'ACCEPTABLE_PLUS',
  SATISFACTORY_MINUS = 'SATISFACTORY_MINUS',
  SATISFACTORY = 'SATISFACTORY',
  SATISFACTORY_PLUS = 'SATISFACTORY_PLUS',
  GOOD_MINUS = 'GOOD_MINUS',
  GOOD = 'GOOD',
  GOOD_PLUS = 'GOOD_PLUS',
  VERY_GOOD_MINUS = 'VERY_GOOD_MINUS',
  VERY_GOOD = 'VERY_GOOD',
  VERY_GOOD_PLUS = 'VERY_GOOD_PLUS',
  EXCELLENT = 'EXCELLENT',
  NO_ASSIGNMENT = 'NO_ASSIGNMENT',
  UNPREPARED = 'UNPREPARED',
  UNCLASSIFIED = 'UNCLASSIFIED',
  ATTENDED = 'ATTENDED',
  DID_NOT_ATTEND = 'ATTEND',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  ABSENT = 'ABSENT',
  EXEMPT = 'EXEMPT',
  PLUS = 'PLUS',
  MINUS = 'MINUS',
}

export const GRADE_SELECT_VALUES = [
  { value: GradeValue.EXCELLENT, label: 'celujący (cel, 6)', group: 'Standardowe' },
  { value: GradeValue.VERY_GOOD_PLUS, label: 'bardzo dobry plus (bdb+, 5+)', group: 'Standardowe' },
  { value: GradeValue.VERY_GOOD, label: 'bardzo dobry (bdb, 5)', group: 'Standardowe' },
  { value: GradeValue.VERY_GOOD_MINUS, label: 'bardzo dobry minus (bdb-, 5-)', group: 'Standardowe' },
  { value: GradeValue.GOOD_PLUS, label: 'dobry plus (db+, 4+)', group: 'Standardowe' },
  { value: GradeValue.GOOD, label: 'dobry (db, 4)', group: 'Standardowe' },
  { value: GradeValue.GOOD_MINUS, label: 'dobry minus (db-, 4-)', group: 'Standardowe' },
  { value: GradeValue.SATISFACTORY_PLUS, label: 'dostateczny plus (dst+, 3+)', group: 'Standardowe' },
  { value: GradeValue.SATISFACTORY, label: 'dostateczny (dst, 3)', group: 'Standardowe' },
  { value: GradeValue.SATISFACTORY_MINUS, label: 'dostateczny minus (dst-, 3-)', group: 'Standardowe' },
  { value: GradeValue.ACCEPTABLE_PLUS, label: 'dopuszczający plus (dop+, 2+)', group: 'Standardowe' },
  { value: GradeValue.ACCEPTABLE, label: 'dopuszczający (dop, 2)', group: 'Standardowe' },
  { value: GradeValue.ACCEPTABLE_MINUS, label: 'dopuszczający minus (dop-, 2-)', group: 'Standardowe' },
  { value: GradeValue.UNSATISFACTORY, label: 'niedostateczny (ndst, 1)', group: 'Standardowe' },
  { value: GradeValue.NO_ASSIGNMENT, label: 'brak zadania (bz)', group: 'Specjalne' },
  { value: GradeValue.UNPREPARED, label: 'nieprzygotowany (np)', group: 'Specjalne' },
  { value: GradeValue.UNCLASSIFIED, label: 'nieklasyfikowany (nk)', group: 'Specjalne' },
  { value: GradeValue.ATTENDED, label: 'uczęszczał (uc)', group: 'Specjalne' },
  { value: GradeValue.DID_NOT_ATTEND, label: 'nie uczęszczał (nu)', group: 'Specjalne' },
  { value: GradeValue.PASSED, label: 'zaliczył (zl)', group: 'Specjalne' },
  { value: GradeValue.FAILED, label: 'nie zaliczył (nz)', group: 'Specjalne' },
  { value: GradeValue.ABSENT, label: 'nieobecny (nb)', group: 'Specjalne' },
  { value: GradeValue.EXEMPT, label: 'zwolniony (zw)', group: 'Specjalne' },
  { value: GradeValue.PLUS, label: 'plus (+)', group: 'Specjalne' },
  { value: GradeValue.MINUS, label: 'minus (-)', group: 'Specjalne' },
];

export const CLASSIFICATION_GRADE_SELECT_VALUES = [
  { value: GradeValue.EXCELLENT, label: 'celujący (cel, 6)', group: 'Standardowe' },
  { value: GradeValue.VERY_GOOD, label: 'bardzo dobry (bdb, 5)', group: 'Standardowe' },
  { value: GradeValue.GOOD, label: 'dobry (db, 4)', group: 'Standardowe' },
  { value: GradeValue.SATISFACTORY, label: 'dostateczny (dst, 3)', group: 'Standardowe' },
  { value: GradeValue.ACCEPTABLE, label: 'dopuszczający (dop, 2)', group: 'Standardowe' },
  { value: GradeValue.UNSATISFACTORY, label: 'niedostateczny (ndst, 1)', group: 'Standardowe' },
  { value: GradeValue.UNCLASSIFIED, label: 'nieklasyfikowany (nk)', group: 'Specjalne' },
  { value: GradeValue.ATTENDED, label: 'uczęszczał (uc)', group: 'Specjalne' },
  { value: GradeValue.DID_NOT_ATTEND, label: 'nie uczęszczał (nu)', group: 'Specjalne' },
  { value: GradeValue.PASSED, label: 'zaliczył (zl)', group: 'Specjalne' },
  { value: GradeValue.FAILED, label: 'nie zaliczył (nz)', group: 'Specjalne' },
  { value: GradeValue.EXEMPT, label: 'zwolniony (zw)', group: 'Specjalne' },
];